#!/bin/bash

set -e

apt-get update -y
apt-get install -y curl

# wait for token generated by server
while [ ! -f /vagrant/node-token ]; do
  echo "Waiting for token..."
  sleep 2
done

TOKEN=$(cat /vagrant/node-token)

# install k3s agent
curl -sfL https://get.k3s.io | K3S_URL="https://192.168.56.110:6443" \
  K3S_TOKEN="$TOKEN" \
  sh -s - agent \
  --node-ip 192.168.56.111

echo "K3s agent installed"